name: Release

on: repository_dispatch

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        if: github.event.action == 'create-release'

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        if: github.event.action == 'create-release'
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: support/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
